package org.integrationuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2016-10-19T19:09:02.386-04:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://integrationuri.org/", name = "WebRouterSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface WebRouterSoap {

    @WebMethod(action = "http://integrationuri.org/route")
    @RequestWrapper(localName = "route", targetNamespace = "http://integrationuri.org/", className = "org.integrationuri.Route")
    @ResponseWrapper(localName = "routeResponse", targetNamespace = "http://integrationuri.org/", className = "org.integrationuri.RouteResponse")
    @WebResult(name = "routeResult", targetNamespace = "http://integrationuri.org/")
    public java.lang.String route(
        @WebParam(name = "inputXml", targetNamespace = "http://integrationuri.org/")
        java.lang.String inputXml
    );
}
