package org.integrationuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2016-10-19T19:09:02.287-04:00
 * Generated source version: 2.7.5
 * 
 */
@WebService(targetNamespace = "http://integrationuri.org/", name = "WebRouterHttpGet")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface WebRouterHttpGet {

    @WebMethod
    @WebResult(name = "string", targetNamespace = "http://integrationuri.org/", partName = "Body")
    public java.lang.String route(
        @WebParam(partName = "inputXml", name = "inputXml", targetNamespace = "")
        java.lang.String inputXml
    );
}
