package org.integrationuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.5
 * 2016-10-19T19:09:02.400-04:00
 * Generated source version: 2.7.5
 * 
 */
@WebServiceClient(name = "WebRouter", 
                  wsdlLocation = "http://krb-jobs.brassring.com/WebRouter/WebRouter.asmx?WSDL",
                  targetNamespace = "http://integrationuri.org/") 
public class WebRouter extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://integrationuri.org/", "WebRouter");
    public final static QName WebRouterHttpGet = new QName("http://integrationuri.org/", "WebRouterHttpGet");
    public final static QName WebRouterSoap = new QName("http://integrationuri.org/", "WebRouterSoap");
    public final static QName WebRouterSoap12 = new QName("http://integrationuri.org/", "WebRouterSoap12");
    public final static QName WebRouterHttpPost = new QName("http://integrationuri.org/", "WebRouterHttpPost");
    static {
        URL url = null;
        try {
            url = new URL("http://krb-jobs.brassring.com/WebRouter/WebRouter.asmx?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WebRouter.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://krb-jobs.brassring.com/WebRouter/WebRouter.asmx?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public WebRouter(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WebRouter(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebRouter() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebRouter(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebRouter(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public WebRouter(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns WebRouterHttpGet
     */
    @WebEndpoint(name = "WebRouterHttpGet")
    public WebRouterHttpGet getWebRouterHttpGet() {
        return super.getPort(WebRouterHttpGet, WebRouterHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebRouterHttpGet
     */
    @WebEndpoint(name = "WebRouterHttpGet")
    public WebRouterHttpGet getWebRouterHttpGet(WebServiceFeature... features) {
        return super.getPort(WebRouterHttpGet, WebRouterHttpGet.class, features);
    }
    /**
     *
     * @return
     *     returns WebRouterSoap
     */
    @WebEndpoint(name = "WebRouterSoap")
    public WebRouterSoap getWebRouterSoap() {
        return super.getPort(WebRouterSoap, WebRouterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebRouterSoap
     */
    @WebEndpoint(name = "WebRouterSoap")
    public WebRouterSoap getWebRouterSoap(WebServiceFeature... features) {
        return super.getPort(WebRouterSoap, WebRouterSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WebRouterSoap
     */
    @WebEndpoint(name = "WebRouterSoap12")
    public WebRouterSoap getWebRouterSoap12() {
        return super.getPort(WebRouterSoap12, WebRouterSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebRouterSoap
     */
    @WebEndpoint(name = "WebRouterSoap12")
    public WebRouterSoap getWebRouterSoap12(WebServiceFeature... features) {
        return super.getPort(WebRouterSoap12, WebRouterSoap.class, features);
    }
    /**
     *
     * @return
     *     returns WebRouterHttpPost
     */
    @WebEndpoint(name = "WebRouterHttpPost")
    public WebRouterHttpPost getWebRouterHttpPost() {
        return super.getPort(WebRouterHttpPost, WebRouterHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WebRouterHttpPost
     */
    @WebEndpoint(name = "WebRouterHttpPost")
    public WebRouterHttpPost getWebRouterHttpPost(WebServiceFeature... features) {
        return super.getPort(WebRouterHttpPost, WebRouterHttpPost.class, features);
    }

}
